# View WB, IMF and Covid data combined

Data is previoiusly saved locally in CSV format, where columns are 'Country or Area', 'Item', 'Year', 'Value'.

In [26]:
import pandas as pd

df=pd.read_csv('IMF_statistics.csv')
df=df.append(pd.read_csv('WB_statistics.csv'))
df=df.append(pd.read_csv('Covid_statistics.csv'))
print('Number of datapoints:',df.shape[0])

Number of datapoints: 4730

In [27]:
print('Indicators in data')
indicators=df.Item.unique()
for x in indicators:
    print(' ',x)
    print('    years:',df[df.Item==x].Year.unique())

Indicators in data
  Central Government Debt (Percent of GDP)
    years: [2017 2018 2019]
  Real GDP growth (Annual percent change)
    years: [2017 2018 2019 2020 2021 2022 2023 2024 2025 2026]
  International tourism, number of arrivals
    years: [2018 2019 2020]
  Unemployment, total (% of total labor force) (modeled ILO estimate)
    years: [2018 2019 2020]
  GDP per capita (current US$)
    years: [2018 2019 2020]
  people_vaccinated_per_hundred
    years: [2021]

In [28]:
df.to_csv('Combined_statistics.csv', index=False)

countries=df['Country or Area'].unique()
print('Number of countries or areas in data:',len(countries))
df[df['Country or Area']=='Finland']

Number of countries or areas in data: 310

,Country or Area,Value,Year,Item,Code3
48,Finland,51.034599,2017,Central Government Debt (Percent of GDP),FIN
198,Finland,49.337077,2018,Central Government Debt (Percent of GDP),FIN
348,Finland,49.128897,2019,Central Government Debt (Percent of GDP),FIN
501,Finland,3.2,2017,Real GDP growth (Annual percent change),FIN
667,Finland,1.3,2018,Real GDP growth (Annual percent change),FIN
833,Finland,1.3,2019,Real GDP growth (Annual percent change),FIN
999,Finland,-2.9,2020,Real GDP growth (Annual percent change),FIN
1165,Finland,2.3,2021,Real GDP growth (Annual percent change),FIN
1331,Finland,2.5,2022,Real GDP growth (Annual percent change),FIN
1497,Finland,1.5,2023,Real GDP growth (Annual percent change),FIN
1663,Finland,1.3,2024,Real GDP growth (Annual percent change),FIN
1829,Finland,1.3,2025,Real GDP growth (Annual percent change),FIN
1995,Finland,1.3,2026,Real GDP growth (Annual percent change),FIN
225,Finland,3224000.0,2018,"International tourism, number of arrivals",FIN
226,Finland,3290000.0,2019,"International tourism, number of arrivals",FIN
227,Finland,NaN,2020,"International tourism, number of arrivals",FIN
1023,Finland,7.36,2018,"Unemployment, total (% of total labor force) (...",FIN
1024,Finland,6.7,2019,"Unemployment, total (% of total labor force) (...",FIN
1025,Finland,7.83,2020,"Unemployment, total (% of total labor force) (...",FIN
1821,Finland,50013.294203,2018,GDP per capita (current US$),FIN
1822,Finland,48711.564208,2019,GDP per capita (current US$),FIN
1823,Finland,49041.342257,2020,GDP per capita (current US$),FIN
71,Finland,74.5,2021,people_vaccinated_per_hundred,FIN

In [29]:
df.shape

(4730, 5)

In [30]:
ccodes=pd.read_csv('countries.csv')[['Code2','Code3','Country or Area']]
ccodes.head()

  Code2 Code3 Country or Area
0    DZ   DZA         Algeria
1    EG   EGY           Egypt
2    LY   LBY           Libya
3    MA   MAR         Morocco
4    SD   SDN           Sudan

In [31]:
df=df.drop(columns={'Country or Area'})

In [37]:
df2=pd.merge(df, ccodes, on=['Code3'], how='left')
df2.head(50)
df2.shape

(4730, 6)

In [38]:
df2.to_csv('Combined_statistics.csv', index=False)

In [40]:
df2[df2.Code3=='USA']

,Value,Year,Item,Code3,Code2,Country or Area
2863,169324921.875,2018,"International tourism, number of arrivals",USA,US,United States of America
2864,166009000.0,2019,"International tourism, number of arrivals",USA,US,United States of America
2865,NaN,2020,"International tourism, number of arrivals",USA,US,United States of America
3661,3.9,2018,"Unemployment, total (% of total labor force) (...",USA,US,United States of America
3662,3.67,2019,"Unemployment, total (% of total labor force) (...",USA,US,United States of America
3663,8.31,2020,"Unemployment, total (% of total labor force) (...",USA,US,United States of America
4459,63064.41841,2018,GDP per capita (current US$),USA,US,United States of America
4460,65279.529026,2019,GDP per capita (current US$),USA,US,United States of America
4461,63543.577789,2020,GDP per capita (current US$),USA,US,United States of America
4719,63.73,2021,people_vaccinated_per_hundred,USA,US,United States of America

In [50]:
df3=df2.dropna()
df3.shape

(3794, 6)

In [51]:
df3.to_csv('Combined_statistics.csv', index=False)