# Classification of countries

Source: https://unstats.un.org/unsd/methodology/m49/overview/

In [5]:
import pandas as pd

df=pd.read_csv('UNSD_countries.csv')

In [7]:
df.head(20)

,Global Code,Global Name,Region Code,Region Name,Sub-region Code,Sub-region Name,Intermediate Region Code,Intermediate Region Name,Country or Area,M49 Code,ISO-alpha2 Code,ISO-alpha3 Code,Least Developed Countries (LDC),Land Locked Developing Countries (LLDC),Small Island Developing States (SIDS),Developed / Developing Countries
0,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Algeria,12,DZ,DZA,NaN,NaN,NaN,Developing
1,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Egypt,818,EG,EGY,NaN,NaN,NaN,Developing
2,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Libya,434,LY,LBY,NaN,NaN,NaN,Developing
3,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Morocco,504,MA,MAR,NaN,NaN,NaN,Developing
4,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Sudan,729,SD,SDN,x,NaN,NaN,Developing
5,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Tunisia,788,TN,TUN,NaN,NaN,NaN,Developing
6,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Western Sahara,732,EH,ESH,NaN,NaN,NaN,Developing
7,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,British Indian Ocean Territory,86,IO,IOT,NaN,NaN,NaN,Developing
8,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Burundi,108,BI,BDI,x,x,NaN,Developing
9,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Comoros,174,KM,COM,x,NaN,x,Developing
10,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Djibouti,262,DJ,DJI,x,NaN,NaN,Developing
11,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Eritrea,232,ER,ERI,x,NaN,NaN,Developing
12,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Ethiopia,231,ET,ETH,x,x,NaN,Developing
13,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,French Southern Territories,260,TF,ATF,NaN,NaN,NaN,Developing
14,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Kenya,404,KE,KEN,NaN,NaN,NaN,Developing
15,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Madagascar,450,MG,MDG,x,NaN,NaN,Developing
16,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Malawi,454,MW,MWI,x,x,NaN,Developing
17,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Mauritius,480,MU,MUS,NaN,NaN,x,Developing
18,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Mayotte,175,YT,MYT,NaN,NaN,NaN,Developing
19,1,World,2.0,Africa,202.0,Sub-Saharan Africa,14.0,Eastern Africa,Mozambique,508,MZ,MOZ,x,NaN,NaN,Developing

In [12]:
df=df.drop(['Global Code','Global Name','Intermediate Region Code','Intermediate Region Name','Intermediate Region Name','Land Locked Developing Countries (LLDC)', 'Small Island Developing States (SIDS)'], axis=1)

In [13]:
df.head()

,Region Code,Region Name,Sub-region Code,Sub-region Name,Country or Area,M49 Code,ISO-alpha2 Code,ISO-alpha3 Code,Least Developed Countries (LDC),Developed / Developing Countries
0,2.0,Africa,15.0,Northern Africa,Algeria,12,DZ,DZA,NaN,Developing
1,2.0,Africa,15.0,Northern Africa,Egypt,818,EG,EGY,NaN,Developing
2,2.0,Africa,15.0,Northern Africa,Libya,434,LY,LBY,NaN,Developing
3,2.0,Africa,15.0,Northern Africa,Morocco,504,MA,MAR,NaN,Developing
4,2.0,Africa,15.0,Northern Africa,Sudan,729,SD,SDN,x,Developing

In [15]:
df=df.rename(columns={'ISO-alpha2 Code':'Code2','ISO-alpha3 Code':'Code3'})

In [20]:
df.shape

(249, 10)

In [21]:
df.to_csv('countries.csv', index=False)